# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pressure_sensors.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(827, 671)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(400, 400))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gl_pmatrix = QtWidgets.QGridLayout()
        self.gl_pmatrix.setObjectName("gl_pmatrix")
        self.gridLayout_3.addLayout(self.gl_pmatrix, 1, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.gridLayout_3.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setMinimumSize(QtCore.QSize(0, 20))
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout.addWidget(self.label_13)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_12.setObjectName("label_12")
        self.horizontalLayout.addWidget(self.label_12)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 6, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.rb_remap = QtWidgets.QRadioButton(self.groupBox_3)
        self.rb_remap.setGeometry(QtCore.QRect(30, 60, 117, 22))
        self.rb_remap.setObjectName("rb_remap")
        self.rb_raw = QtWidgets.QRadioButton(self.groupBox_3)
        self.rb_raw.setGeometry(QtCore.QRect(30, 30, 117, 22))
        self.rb_raw.setChecked(True)
        self.rb_raw.setObjectName("rb_raw")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_4.setGeometry(QtCore.QRect(170, 0, 201, 191))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.rb_sensval = QtWidgets.QRadioButton(self.groupBox_4)
        self.rb_sensval.setGeometry(QtCore.QRect(30, 30, 117, 22))
        self.rb_sensval.setChecked(True)
        self.rb_sensval.setObjectName("rb_sensval")
        self.rb_interp = QtWidgets.QRadioButton(self.groupBox_4)
        self.rb_interp.setGeometry(QtCore.QRect(30, 60, 117, 22))
        self.rb_interp.setObjectName("rb_interp")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_5.setGeometry(QtCore.QRect(40, 160, 121, 27))
        self.pushButton_5.setObjectName("pushButton_5")
        self.sl_zoom = QtWidgets.QSlider(self.groupBox_4)
        self.sl_zoom.setGeometry(QtCore.QRect(20, 130, 160, 29))
        self.sl_zoom.setMinimum(2)
        self.sl_zoom.setMaximum(7)
        self.sl_zoom.setOrientation(QtCore.Qt.Horizontal)
        self.sl_zoom.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.sl_zoom.setTickInterval(1)
        self.sl_zoom.setObjectName("sl_zoom")
        self.label_20 = QtWidgets.QLabel(self.groupBox_4)
        self.label_20.setGeometry(QtCore.QRect(20, 100, 91, 17))
        self.label_20.setObjectName("label_20")
        self.lbl_zoom = QtWidgets.QLabel(self.groupBox_4)
        self.lbl_zoom.setGeometry(QtCore.QRect(167, 100, 21, 20))
        self.lbl_zoom.setObjectName("lbl_zoom")
        self.cb_showVals = QtWidgets.QCheckBox(self.groupBox_3)
        self.cb_showVals.setGeometry(QtCore.QRect(30, 100, 121, 22))
        self.cb_showVals.setChecked(True)
        self.cb_showVals.setObjectName("cb_showVals")
        self.gridLayout.addWidget(self.groupBox_3, 7, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 2, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 2, 2, 1, 1)
        self.hs_delay2 = QtWidgets.QSlider(self.centralwidget)
        self.hs_delay2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.hs_delay2.setOrientation(QtCore.Qt.Horizontal)
        self.hs_delay2.setObjectName("hs_delay2")
        self.gridLayout.addWidget(self.hs_delay2, 4, 2, 1, 1)
        self.hs_delay1 = QtWidgets.QSlider(self.centralwidget)
        self.hs_delay1.setMaximumSize(QtCore.QSize(200, 16777215))
        self.hs_delay1.setOrientation(QtCore.Qt.Horizontal)
        self.hs_delay1.setObjectName("hs_delay1")
        self.gridLayout.addWidget(self.hs_delay1, 3, 2, 1, 1)
        self.sl_pwm_value = QtWidgets.QSlider(self.centralwidget)
        self.sl_pwm_value.setMaximumSize(QtCore.QSize(200, 16777215))
        self.sl_pwm_value.setMaximum(255)
        self.sl_pwm_value.setOrientation(QtCore.Qt.Horizontal)
        self.sl_pwm_value.setObjectName("sl_pwm_value")
        self.gridLayout.addWidget(self.sl_pwm_value, 5, 2, 1, 1)
        self.lbl_delay1 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_delay1.setMinimumSize(QtCore.QSize(100, 0))
        self.lbl_delay1.setText("")
        self.lbl_delay1.setObjectName("lbl_delay1")
        self.gridLayout.addWidget(self.lbl_delay1, 3, 3, 1, 1)
        self.lbl_delay2 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_delay2.setMinimumSize(QtCore.QSize(100, 0))
        self.lbl_delay2.setText("")
        self.lbl_delay2.setObjectName("lbl_delay2")
        self.gridLayout.addWidget(self.lbl_delay2, 4, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(200, 200))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(29, 60, 141, 131))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gl_minmax = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gl_minmax.setObjectName("gl_minmax")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 60, 31, 131))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_14.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_14.setObjectName("label_14")
        self.verticalLayout_2.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_15.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_15.setObjectName("label_15")
        self.verticalLayout_2.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_16.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_16.setObjectName("label_16")
        self.verticalLayout_2.addWidget(self.label_16)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 20, 171, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_17 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_17.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_2.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_18.setMaximumSize(QtCore.QSize(20, 20))
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_2.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_19.setMaximumSize(QtCore.QSize(20, 20))
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_2.addWidget(self.label_19)
        self.gridLayout.addWidget(self.groupBox_2, 7, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 1, 1, 1)
        self.lbl_pwm = QtWidgets.QLabel(self.centralwidget)
        self.lbl_pwm.setMinimumSize(QtCore.QSize(100, 0))
        self.lbl_pwm.setText("")
        self.lbl_pwm.setObjectName("lbl_pwm")
        self.gridLayout.addWidget(self.lbl_pwm, 5, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 827, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.hs_delay1.sliderMoved['int'].connect(self.lbl_delay1.setNum)
        self.hs_delay2.sliderMoved['int'].connect(self.lbl_delay2.setNum)
        self.sl_pwm_value.sliderMoved['int'].connect(self.lbl_pwm.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Matrix"))
        self.label_9.setText(_translate("MainWindow", "A"))
        self.label_8.setText(_translate("MainWindow", "B"))
        self.label_7.setText(_translate("MainWindow", "C"))
        self.label_10.setText(_translate("MainWindow", "1"))
        self.label_11.setText(_translate("MainWindow", "2"))
        self.label_12.setText(_translate("MainWindow", "3"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Settings"))
        self.rb_remap.setText(_translate("MainWindow", "Remapping"))
        self.rb_raw.setText(_translate("MainWindow", "Raw data"))
        self.rb_sensval.setText(_translate("MainWindow", "Sensors only"))
        self.rb_interp.setText(_translate("MainWindow", "Interpolation"))
        self.pushButton_5.setText(_translate("MainWindow", "Reset Min/Max"))
        self.label_20.setText(_translate("MainWindow", "Zoom factor"))
        self.lbl_zoom.setText(_translate("MainWindow", "2"))
        self.cb_showVals.setText(_translate("MainWindow", "Show Values"))
        self.pushButton.setText(_translate("MainWindow", "No User"))
        self.pushButton_2.setText(_translate("MainWindow", "Human User"))
        self.pushButton_3.setText(_translate("MainWindow", "Robot User"))
        self.label_5.setText(_translate("MainWindow", "Delay2"))
        self.label_6.setText(_translate("MainWindow", "pwm"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Min/Max values"))
        self.label_14.setText(_translate("MainWindow", "A"))
        self.label_15.setText(_translate("MainWindow", "B"))
        self.label_16.setText(_translate("MainWindow", "C"))
        self.label_17.setText(_translate("MainWindow", "1"))
        self.label_18.setText(_translate("MainWindow", "2"))
        self.label_19.setText(_translate("MainWindow", "3"))
        self.label_4.setText(_translate("MainWindow", "Delay1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

